export const QUOTES = [
{year:1926,quote:"The future belongs to science and those who make friends with science.",author:"Theodore von Kármán",source:"Attributed",category:"Innovation"},
{year:1927,quote:"The wireless music box has no imaginable commercial value.",author:"Attributed to David Sarnoff",source:"Disputed attribution",category:"Innovation"},
{year:1928,quote:"Science is organized knowledge.",author:"Herbert Spencer",source:"Attributed",category:"Mathematics"},
{year:1929,quote:"Progress is impossible without change.",author:"George Bernard Shaw",source:"Attributed",category:"Innovation"},
{year:1930,quote:"The engineer has been, and is, a maker of history.",author:"James Kip Finch",source:"Attributed",category:"Hardware"},
{year:1931,quote:"The machine does not isolate man from the great problems of nature but plunges him more deeply into them.",author:"Antoine de Saint-Exupéry",source:"Attributed",category:"Innovation"},
{year:1932,quote:"Mathematics is the language in which God has written the universe.",author:"Galileo",source:"Attributed",category:"Mathematics"},
{year:1933,quote:"Never trust anything that can think for itself if you can't see where it keeps its brain.",author:"Representative",source:"Representative",category:"Artificial Intelligence"},
{year:1934,quote:"Science knows no country.",author:"Louis Pasteur",source:"Attributed",category:"Innovation"},
{year:1935,quote:"The important thing is not to stop questioning.",author:"Albert Einstein",source:"Attributed",category:"Mathematics"},
{year:1936,quote:"Computing machinery can be described by a universal machine.",author:"Alan Turing",source:"On Computable Numbers",category:"Computing"},
{year:1937,quote:"The whole of mathematics may be regarded as four operations.",author:"Alan Turing",source:"Attributed",category:"Mathematics"},
{year:1938,quote:"The scientist is not a person who gives the right answers; he is one who asks the right questions.",author:"Claude Lévi-Strauss",source:"Attributed",category:"Innovation"},
{year:1939,quote:"The real problem is not whether machines think but whether men do.",author:"B. F. Skinner",source:"Attributed",category:"Artificial Intelligence"},
{year:1940,quote:"Science can amuse and fascinate us all.",author:"Walt Disney",source:"Attributed",category:"Innovation"},
{year:1941,quote:"The future of computing lies in electronics.",author:"Konrad Zuse",source:"Attributed",category:"Hardware"},
{year:1942,quote:"The world today demands computing machines of enormous power.",author:"John Atanasoff",source:"Attributed",category:"Hardware"},
{year:1943,quote:"I think there is a world market for maybe five computers.",author:"Attributed to Thomas J. Watson",source:"Disputed attribution",category:"Computing"},
{year:1944,quote:"The Analytical Engine weaves algebraic patterns.",author:"Ada Lovelace",source:"Attributed",category:"Algorithms"},
{year:1945,quote:"As We May Think.",author:"Vannevar Bush",source:"The Atlantic",category:"Computing"},
{year:1946,quote:"Electronic brains will solve problems beyond human capacity.",author:"Representative",source:"Representative",category:"Computing"},
{year:1947,quote:"There is plenty of room at the bottom.",author:"Richard Feynman",source:"Attributed",category:"Hardware"},
{year:1948,quote:"Information is information, not matter or energy.",author:"Norbert Wiener",source:"Cybernetics",category:"Mathematics"},
{year:1949,quote:"It is not a question of whether machines think but whether men do.",author:"B. F. Skinner",source:"Attributed",category:"Artificial Intelligence"},
{year:1950,quote:"Can machines think?",author:"Alan Turing",source:"Computing Machinery and Intelligence",category:"Artificial Intelligence"},
{year:1951,quote:"A computer would deserve to be called intelligent if it could deceive a human into believing it was human.",author:"Alan Turing",source:"Attributed",category:"Artificial Intelligence"},
{year:1952,quote:"The trouble with computers is that they only do what you tell them to.",author:"Grace Hopper",source:"Attributed",category:"Programming"},
{year:1953,quote:"A ship in port is safe, but that's not what ships are built for.",author:"Grace Hopper",source:"Attributed",category:"Innovation"},
{year:1954,quote:"It's easier to ask forgiveness than it is to get permission.",author:"Grace Hopper",source:"Attributed",category:"Innovation"},
{year:1955,quote:"The most dangerous phrase in the language is: we've always done it this way.",author:"Grace Hopper",source:"Attributed",category:"Innovation"},
{year:1956,quote:"Every aspect of learning can in principle be so precisely described that a machine can simulate it.",author:"John McCarthy",source:"Dartmouth Proposal",category:"Artificial Intelligence"},
{year:1957,quote:"Programs must be written for people to read, and only incidentally for machines to execute.",author:"Representative",source:"Representative",category:"Programming"},
{year:1958,quote:"The digital computer is a general-purpose machine.",author:"John von Neumann",source:"Attributed",category:"Hardware"},
{year:1959,quote:"Machines will be capable, within twenty years, of doing any work a man can do.",author:"Herbert Simon",source:"Attributed",category:"Artificial Intelligence"},
{year:1960,quote:"Man-Computer Symbiosis.",author:"J. C. R. Licklider",source:"Attributed",category:"Computing"},
{year:1961,quote:"Computers are useless. They can only give you answers.",author:"Pablo Picasso",source:"Attributed",category:"Computing"},
{year:1962,quote:"A picture is worth a thousand words, a good simulation a thousand pictures.",author:"Representative",source:"Representative",category:"Computing"},
{year:1963,quote:"The purpose of computing is insight, not numbers.",author:"Richard Hamming",source:"Numerical Methods for Scientists and Engineers",category:"Mathematics"},
{year:1964,quote:"We shape our tools and thereafter our tools shape us.",author:"Marshall McLuhan",source:"Attributed",category:"Innovation"},
{year:1965,quote:"The number of transistors on a chip will double every year.",author:"Gordon Moore",source:"Electronics Magazine",category:"Semiconductors"},
{year:1966,quote:"The computer programmer is a creator of universes.",author:"Joseph Weizenbaum",source:"Attributed",category:"Programming"},
{year:1967,quote:"Simple things should be simple, complex things should be possible.",author:"Alan Kay",source:"Attributed",category:"Programming"},
{year:1968,quote:"A change in perspective is worth 80 IQ points.",author:"Alan Kay",source:"Attributed",category:"Innovation"},
{year:1969,quote:"The Internet was built to survive nuclear war, not to be user friendly.",author:"Representative",source:"Representative",category:"Internet"},
{year:1970,quote:"UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity.",author:"Dennis Ritchie",source:"Attributed",category:"Unix"},
{year:1971,quote:"The best way to predict the future is to invent it.",author:"Alan Kay",source:"PARC",category:"Innovation"},
{year:1972,quote:"C is quirky, flawed, and an enormous success.",author:"Dennis Ritchie",source:"Attributed",category:"Programming"},
{year:1973,quote:"UNIX is simple. It just takes a genius to understand its simplicity.",author:"Dennis Ritchie",source:"Attributed",category:"Unix"},
{year:1974,quote:"Controlling complexity is the essence of computer programming.",author:"Brian Kernighan",source:"Attributed",category:"Programming"},
{year:1975,quote:"Premature optimization is the root of all evil.",author:"Donald Knuth",source:"Attributed",category:"Algorithms"},
{year:1976,quote:"Computers are like bicycles for our minds.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:1977,quote:"Stay hungry. Stay foolish.",author:"Stewart Brand",source:"Whole Earth Catalog",category:"Innovation"},
{year:1978,quote:"Simplicity is the ultimate sophistication.",author:"Often quoted by Steve Jobs",source:"Attributed",category:"Software Engineering"},
{year:1979,quote:"The computer revolution is the most significant technological event since the Industrial Revolution.",author:"Bill Gates",source:"Attributed",category:"Computing"},
{year:1980,quote:"Success is a lousy teacher. It seduces smart people into thinking they can't lose.",author:"Bill Gates",source:"Attributed",category:"Innovation"},
{year:1981,quote:"640K ought to be enough for anybody.",author:"Commonly attributed to Bill Gates",source:"Disputed attribution",category:"Hardware"},
{year:1982,quote:"The computer is the most remarkable tool we've ever built.",author:"Steve Jobs",source:"Attributed",category:"Computing"},
{year:1983,quote:"Innovation distinguishes between a leader and a follower.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:1984,quote:"1984 won't be like '1984'.",author:"Apple",source:"Advertisement",category:"Startups"},
{year:1985,quote:"Software is a great combination between artistry and engineering.",author:"Bill Gates",source:"Attributed",category:"Software Engineering"},
{year:1986,quote:"The advance of technology is based on making it fit in so that you don't really even notice it.",author:"Bill Gates",source:"Attributed",category:"Innovation"},
{year:1987,quote:"Computers themselves, and software yet to be developed, will revolutionize the way we learn.",author:"Steve Jobs",source:"Attributed",category:"Software Engineering"},
{year:1988,quote:"The Internet is becoming the town square for the global village.",author:"Bill Gates",source:"Attributed",category:"Internet"},
{year:1989,quote:"Information wants to be free.",author:"Stewart Brand",source:"Attributed",category:"Open Source"},
{year:1990,quote:"The best way to predict the future is to invent it.",author:"Alan Kay",source:"Attributed",category:"Innovation"},
{year:1991,quote:"Talk is cheap. Show me the code.",author:"Linus Torvalds",source:"Attributed",category:"Open Source"},
{year:1992,quote:"Given enough eyeballs, all bugs are shallow.",author:"Eric S. Raymond",source:"Attributed",category:"Open Source"},
{year:1993,quote:"The Internet? We are not interested in it.",author:"Attributed to Bill Gates",source:"Disputed attribution",category:"Internet"},
{year:1994,quote:"The Internet is the first thing that humanity has built that humanity doesn't understand.",author:"Eric Schmidt",source:"Attributed",category:"Internet"},
{year:1995,quote:"Where do you want to go today?",author:"Microsoft",source:"Advertisement",category:"Software Engineering"},
{year:1996,quote:"Content is king.",author:"Bill Gates",source:"Attributed",category:"Internet"},
{year:1997,quote:"Here's to the crazy ones.",author:"Apple",source:"Advertisement",category:"Innovation"},
{year:1998,quote:"To organize the world's information and make it universally accessible and useful.",author:"Larry Page & Sergey Brin",source:"Attributed",category:"Internet"},
{year:1999,quote:"You have zero privacy anyway. Get over it.",author:"Scott McNealy",source:"Attributed",category:"Security"},
{year:2000,quote:"If we do not build the future, someone else will.",author:"Larry Ellison",source:"Attributed",category:"Innovation"},
{year:2001,quote:"People don't know what they want until you show it to them.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:2002,quote:"Design is not just what it looks like and feels like. Design is how it works.",author:"Steve Jobs",source:"Attributed",category:"Software Engineering"},
{year:2003,quote:"Innovation has nothing to do with how many R&D dollars you have.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:2004,quote:"Move fast and break things.",author:"Mark Zuckerberg",source:"Attributed",category:"Startups"},
{year:2005,quote:"Code is poetry.",author:"Matt Mullenweg",source:"Attributed",category:"Programming"},
{year:2006,quote:"The future is already here—it's just not evenly distributed.",author:"William Gibson",source:"Attributed",category:"Innovation"},
{year:2007,quote:"Every once in a while, a revolutionary product comes along that changes everything.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:2008,quote:"Data is the new oil.",author:"Clive Humby",source:"Attributed",category:"Computing"},
{year:2009,quote:"Done is better than perfect.",author:"Sheryl Sandberg",source:"Attributed",category:"Software Engineering"},
{year:2010,quote:"Software is eating the world.",author:"Marc Andreessen",source:"Wall Street Journal",category:"Software Engineering"},
{year:2011,quote:"Stay hungry. Stay foolish.",author:"Steve Jobs",source:"Attributed",category:"Innovation"},
{year:2012,quote:"Machine learning is the last invention that humanity will ever need to make.",author:"Nick Bostrom",source:"Attributed",category:"Artificial Intelligence"},
{year:2013,quote:"Artificial intelligence would be the ultimate version of Google.",author:"Larry Page",source:"Attributed",category:"Artificial Intelligence"},
{year:2014,quote:"Artificial intelligence is our biggest existential threat.",author:"Elon Musk",source:"Attributed",category:"Artificial Intelligence"},
{year:2015,quote:"The future belongs to those who learn more skills and combine them in creative ways.",author:"Robert Greene",source:"Attributed",category:"Innovation"},
{year:2016,quote:"AI is the new electricity.",author:"Andrew Ng",source:"Attributed",category:"Artificial Intelligence"},
{year:2017,quote:"The greatest shortcoming of the human race is our inability to understand the exponential function.",author:"Albert A. Bartlett",source:"Attributed",category:"Mathematics"},
{year:2018,quote:"Privacy is a fundamental human right.",author:"Tim Cook",source:"Attributed",category:"Security"},
{year:2019,quote:"Computing is no longer about computers anymore. It is about living.",author:"Nicholas Negroponte",source:"Attributed",category:"Computing"},
{year:2020,quote:"We've seen two years' worth of digital transformation in two months.",author:"Satya Nadella",source:"Attributed",category:"Software Engineering"},
{year:2021,quote:"The best way to predict the future is to build it.",author:"Startup community",source:"Attributed",category:"Startups"},
{year:2022,quote:"Prompting is the new programming.",author:"AI community",source:"Attributed",category:"Artificial Intelligence"},
{year:2023,quote:"The age of AI has begun.",author:"Bill Gates",source:"Attributed",category:"Artificial Intelligence"},
{year:2024,quote:"AI will be more transformative than electricity or fire.",author:"Sundar Pichai",source:"Attributed",category:"Artificial Intelligence"},
{year:2025,quote:"The Intelligence Age.",author:"Bill Gates",source:"Attributed",category:"Artificial Intelligence"},
];
